version: '3.8' 
services:
  koishi:
    container_name: Koishi
    image: koishijs/koishi
    ports:
      - '5140:5140'
    volumes:
      - './koishi:/koishi'
    environment:
      - 'TZ=Asia/Shanghai'
    network_mode: 'bridge'